import type { Metadata } from "next";
import Link from "next/link";
import { InfoPage, InfoSection } from "@/components/InfoPage";
import { legalContentReviewed } from "@/lib/site-info";
export const metadata: Metadata = { title: "Condiciones de uso", description: "Reglas de uso de Tripu, convivencia, contenido compartido y packs.", robots: { index: legalContentReviewed, follow: true } };

export default function TermsPage() {
  return <InfoPage eyebrow="Un buen viaje para todos" title="Condiciones de uso" intro="Las reglas del juego son importantes. Respetar a las personas con las que juegas lo es todavía más." legal>
    <InfoSection id="participacion" title="1. Participación y cuenta"><p>Para crear o participar en un viaje necesitas identificarte con Google. Reclama únicamente tu nombre y no accedas a la cuenta de otra persona. El creador configura los participantes, las cartas y el tiempo de respuesta y decide cuándo iniciar y finalizar la partida.</p></InfoSection>
    <InfoSection id="limites" title="2. Jugad con límites compartidos"><p>Todos los retos son voluntarios. El grupo debe acordar qué cartas encajan con sus integrantes y su entorno. Nadie está obligado a consumir alcohol, gastar dinero, revelar información personal o realizar una actividad que le incomode.</p><p>Una jugada aceptada o expirada es un estado del juego, no un consentimiento para una actividad real. No utilices las cartas para acosar, discriminar, humillar ni poner en peligro a nadie. Las propuestas relacionadas con alcohol deben limitarse a quienes tengan la edad legal y pueden adaptarse a bebidas sin alcohol.</p></InfoSection>
    <InfoSection id="partida" title="3. Reglas de las partidas"><p>Al iniciar se reparten las manos y se cierra la configuración. Las cartas usadas quedan bloqueadas. Los ataques pendientes se aplican al vencer el plazo y también al finalizar el viaje. Las devoluciones no permiten reacciones encadenadas.</p><p>Necesitas conexión a internet. Un fallo de conexión puede retrasar la visualización de las jugadas; el tiempo de respuesta sigue transcurriendo. Consulta las <Link href="/faq">preguntas frecuentes</Link> antes de empezar.</p></InfoSection>
    <InfoSection id="comunidad" title="4. Propuestas, vídeos e imágenes"><p>Comparte solo contenido propio o para el que tengas permiso, incluyendo el de las personas que aparecen. Las propuestas de cartas y los vídeos pasan por revisión y pueden no publicarse. El nombre de crédito y los datos que acompañen a un vídeo aprobado pueden mostrarse públicamente.</p><p>Respeta la privacidad del grupo al reenviar invitaciones, capturas o resúmenes. Puedes comunicar incidencias sobre un contenido mediante el canal indicado en <Link href="/contacto">Contacto</Link>.</p></InfoSection>
    <InfoSection id="packs" title="5. Packs y pagos"><p>Cuando los pagos están desactivados, los packs se ofrecen abiertos durante las pruebas. Si están habilitados, antes de pagar se muestra el precio y si el acceso se concede para un viaje o para la cuenta. La compra se tramita en Stripe.</p><p>Esta página no sustituye unas condiciones de contratación completas. Antes de comercializar packs, el titular debe completar la información fiscal y de contratación que corresponda, la atención de incidencias, el alcance y duración del acceso y la información aplicable sobre desistimiento y devoluciones. Ningún texto de esta página excluye derechos legales de los consumidores.</p></InfoSection>
    <InfoSection id="cambios" title="6. Disponibilidad y cambios"><p>La aplicación y el catálogo pueden evolucionar, y puede haber interrupciones por mantenimiento. Los cambios relevantes en las condiciones deben comunicarse de forma accesible y respetar los derechos que correspondan. Los datos se tratan conforme a la <Link href="/privacidad">política de privacidad</Link>.</p></InfoSection>
  </InfoPage>;
}
