import type { Metadata } from "next";
import Link from "next/link";
import { ContactEmail, InfoPage, InfoSection } from "@/components/InfoPage";
import { legalContentReviewed, siteOperator } from "@/lib/site-info";

export const metadata: Metadata = { title: "Privacidad", description: "Cómo utiliza Tripu tus datos y cómo ejercer tus derechos.", robots: { index: legalContentReviewed, follow: true } };

export default function PrivacyPage() {
  return <InfoPage eyebrow="Tu información, explicada" title="Política de privacidad" intro="Usamos tus datos para identificarte, guardar las partidas y ofrecer las funciones que eliges." legal>
    <InfoSection id="responsable" title="1. Responsable y contacto"><p>{siteOperator.name}, en {siteOperator.country}, es el responsable del tratamiento de datos de Tripu. Puedes escribir a <ContactEmail subject="Consulta de privacidad" /> y consultar el <Link href="/aviso-legal">aviso legal</Link>.</p></InfoSection>
    <InfoSection id="datos" title="2. Qué datos usamos y para qué"><ul>
      <li><strong>Cuenta y partidas:</strong> datos de tu perfil de Google, correo, sesión, viajes, participantes y jugadas para prestar el servicio que solicitas. La base es la ejecución de esa relación de servicio. No recibimos tu contraseña de Google. El creador del viaje puede introducir los nombres iniciales de sus participantes.</li>
      <li><strong>Aportaciones:</strong> propuestas, comentarios, valoraciones y vídeos que envías para su gestión y, cuando corresponda, publicación tras revisión.</li>
      <li><strong>Funciones opcionales:</strong> datos de suscripción para enviarte notificaciones cuando las activas. Los vídeos de TikTok se cargan cuando lo autorizas. Puedes desactivar estas funciones.</li>
      <li><strong>Uso de la app:</strong> registros de funcionamiento y actividad, incluidas acciones de compartir asociadas a tu cuenta, para mantener y mejorar el servicio.</li>
      <li><strong>Compras, si las realizas:</strong> importe, producto y estado del pago para gestionar la compra y las obligaciones legales aplicables. Stripe procesa el pago; Tripu no guarda el número completo de tu tarjeta.</li>
    </ul></InfoSection>
    <InfoSection id="visibilidad" title="3. Quién puede ver tus datos"><p>Tu mano es privada para tu cuenta. Los participantes ven la actividad del viaje. Quien tenga el enlace o código de invitación puede ver el nombre del viaje, los participantes, sus avatares y un resumen del reparto, incluso sin iniciar sesión.</p><p>Los vídeos aprobados y sus datos de autor, destino y viaje, así como los créditos de cartas, pueden ser públicos. Los resúmenes que compartas pueden incluir nombres y resultados. La administración accede a la información necesaria para gestionar el servicio y atender incidencias.</p></InfoSection>
    <InfoSection id="proveedores" title="4. Proveedores"><p>Utilizamos Google para iniciar sesión, Vercel y Neon para alojar la app y sus datos, y Stripe para los pagos. Si activas notificaciones o vídeos, también intervienen el servicio de avisos de tu navegador y TikTok, respectivamente.</p><p>Según el servicio y su configuración, estos proveedores pueden tratar datos fuera del Espacio Económico Europeo. Las ubicaciones y garantías aplicables siguen en revisión; consulta el apartado de <a href="#revision">información pendiente</a>.</p></InfoSection>
    <InfoSection id="conservacion" title="5. Conservación"><p>Las cuentas, los viajes y sus historiales no se borran automáticamente por antigüedad ni al finalizar la partida. Cerrar sesión tampoco los elimina. Puedes solicitar la supresión por correo. Las suscripciones a notificaciones se eliminan al desactivarlas desde la app o cuando el proveedor comunica su caducidad.</p><p>Los plazos o criterios de conservación de cuentas, aportaciones, actividad y compras aún están pendientes de concretar.</p></InfoSection>
    <InfoSection id="derechos" title="6. Tus derechos"><p>Escribe a <ContactEmail subject="Solicitud de derechos sobre mis datos" /> para solicitar acceso, rectificación, supresión, oposición, limitación o portabilidad, según corresponda.</p><p>Puedes retirar tu consentimiento para las funciones opcionales sin afectar a lo realizado antes: desactiva las notificaciones o utiliza «Ocultar vídeo». No tomamos decisiones automatizadas con efectos jurídicos basadas en tus partidas. Puedes reclamar ante la <a href="https://www.aepd.es/">Agencia Española de Protección de Datos</a>.</p><p>Consulta también cómo gestionar el navegador en <Link href="/cookies">Cookies</Link>.</p></InfoSection>
    {!legalContentReviewed && <InfoSection id="revision" title="Información pendiente"><p>Esta política está en revisión: faltan la base jurídica de las estadísticas de uso, los plazos de conservación y la confirmación de las garantías para transferencias internacionales. Publicaremos aquí la información cuando esté definida.</p></InfoSection>}
  </InfoPage>;
}
