import type { Metadata } from "next";
import Link from "next/link";
import { ContactEmail, InfoPage, InfoSection } from "@/components/InfoPage";
import { legalContentReviewed, siteOperator } from "@/lib/site-info";
export const metadata: Metadata = { title: "Privacidad", description: "Qué datos utiliza Tripu, para qué se usan y cómo gestionar tus derechos.", robots: { index: legalContentReviewed, follow: true } };

export default function PrivacyPage() {
  return <InfoPage eyebrow="Tu información, explicada" title="Política de privacidad" intro="Para jugar necesitamos identificar tu cuenta y guardar las partidas. Aquí explicamos también las funciones opcionales y la visibilidad de lo que compartes." legal>
    <InfoSection id="responsable" title="1. Responsable y contacto"><p>El responsable del tratamiento es {siteOperator.name}, titular de Tripu, un proyecto personal gestionado desde {siteOperator.country} y accesible a cualquier persona con la URL. Puedes consultar sus datos en el <Link href="/aviso-legal#titular">aviso legal</Link> y enviar tus consultas de privacidad a:</p><p><ContactEmail subject="Consulta de privacidad" /></p></InfoSection>
    <InfoSection id="datos" title="2. Qué información se utiliza"><ul>
      <li><strong>Cuenta:</strong> identificador de Google, nombre, correo electrónico, imagen de perfil y datos técnicos de autenticación y sesión. Tripu no recibe tu contraseña de Google.</li>
      <li><strong>Partidas:</strong> nombre del viaje, participantes, nombres elegidos, cartas, jugadas, fechas, resultados e historial. Los nombres iniciales pueden haber sido introducidos por el creador del viaje.</li>
      <li><strong>Aportaciones:</strong> valoraciones, comentarios, propuestas de cartas, nombre para los créditos y enlaces de vídeos con el título, destino y viaje que decidas asociar.</li>
      <li><strong>Notificaciones:</strong> si las activas, se guarda la suscripción de tu navegador, sus claves técnicas y una descripción del navegador para enviarte avisos.</li>
      <li><strong>Compras:</strong> cuando se habilitan pagos, se guardan el pack, modalidad, importe, estado y referencias de Stripe. El pago se introduce en Stripe; Tripu no almacena el número completo de tu tarjeta.</li>
      <li><strong>Funcionamiento del servicio:</strong> registros técnicos del alojamiento y eventos internos, como acciones de compartir una invitación, carta o resumen, asociados a tu cuenta cuando has iniciado sesión.</li>
    </ul></InfoSection>
    <InfoSection id="finalidades" title="3. Para qué se utiliza y base del tratamiento"><p>La gestión de tu cuenta, las partidas y los desbloqueos que solicites permite prestar el servicio; su base es la ejecución de esa relación de servicio. Las obligaciones legales aplicables a compras pueden exigir conservar determinados registros.</p><p>Las notificaciones del navegador y la carga de vídeos externos se activan por tu elección y puedes retirarlas. Las aportaciones a la comunidad se tramitan cuando las envías para su revisión y posible publicación.</p><p>También se calculan estadísticas internas sobre el uso de las partidas y las acciones de compartir para mejorar Tripu. El titular debe completar la evaluación de su base jurídica, los plazos de conservación y las garantías de los proveedores antes de dar esta política por definitiva.</p></InfoSection>
    <InfoSection id="visibilidad" title="4. Quién puede ver la información"><p>Los participantes y el creador acceden a la actividad del viaje. Tu mano se muestra a tu cuenta; los demás ven recuentos y las cartas que se juegan. Las personas con el enlace o código de invitación pueden ver el nombre del viaje, la lista de participantes con sus avatares y un resumen del reparto, incluso antes de entrar.</p><p>Los vídeos aprobados se publican en Comunidad junto con el nombre de quien los envía, el título, destino y nombre del viaje asociado, cuando se hayan indicado. El nombre de crédito de una carta aprobada también puede ser público. Los resúmenes que compartas pueden mostrar nombres y resultados.</p><p>La administración dispone de herramientas para gestionar cartas, revisar aportaciones, atender incidencias y consultar compras y métricas. No incluyas información sensible en nombres de viajes, comentarios o propuestas.</p></InfoSection>
    <InfoSection id="proveedores" title="5. Servicios que intervienen"><ul>
      <li><strong>Google:</strong> identificación de la cuenta y perfil durante el inicio de sesión.</li>
      <li><strong>Vercel y Neon:</strong> alojamiento de la aplicación y almacenamiento de datos, respectivamente.</li>
      <li><strong>Stripe:</strong> tramitación del pago cuando eliges comprar un pack.</li>
      <li><strong>Proveedor de notificaciones de tu navegador:</strong> entrega de avisos cuando los activas.</li>
      <li><strong>TikTok:</strong> carga del reproductor solo cuando lo autorizas, o cuando visitas su web mediante un enlace.</li>
    </ul><p>Estos proveedores pueden tratar datos fuera del Espacio Económico Europeo, según su servicio y configuración. Las regiones, entidades contratadas y garantías de transferencias internacionales están pendientes de confirmar por el titular; no se afirma que todos los datos se almacenen exclusivamente en España o la UE.</p></InfoSection>
    <InfoSection id="conservacion" title="6. Cuánto tiempo se conserva"><p>Los viajes y sus historiales siguen guardados al finalizar la partida. Actualmente no hay un borrado automático de cuentas o partidas por antigüedad. Las suscripciones push se eliminan al desactivarlas desde la app o cuando el proveedor informa de que han caducado.</p><p>El titular debe concretar los plazos de conservación de cuentas, aportaciones, registros de uso y compras. Cerrar sesión elimina el acceso de esa sesión, pero no borra tu cuenta ni sus datos.</p></InfoSection>
    <InfoSection id="derechos" title="7. Tus derechos y preferencias"><p>Puedes solicitar acceso, rectificación, supresión, limitación, portabilidad u oposición, según corresponda, y retirar el consentimiento de las funciones opcionales. Envía estas solicitudes a <ContactEmail subject="Solicitud de derechos sobre mis datos" />. No hay todavía una opción de eliminación de cuenta dentro de la aplicación.</p><p>Puedes desactivar las notificaciones desde el viaje o el navegador, y ocultar un vídeo externo desde su propio control. La retirada no afecta al tratamiento realizado anteriormente.</p><p>Si consideras que se vulneran tus derechos, puedes presentar una reclamación ante la <a href="https://www.aepd.es/">Agencia Española de Protección de Datos</a>. No se utilizan las partidas para adoptar decisiones automatizadas con efectos jurídicos sobre ti.</p></InfoSection>
    <InfoSection id="cookies" title="8. Cookies y cambios"><p>Consulta las cookies de sesión y la carga de contenidos externos en la <Link href="/cookies">política de cookies</Link>. Esta página se actualizará cuando cambien los tratamientos o se concreten los plazos de conservación y las garantías pendientes.</p></InfoSection>
  </InfoPage>;
}
