import type { Metadata } from "next";
import Link from "next/link";
import { InfoPage, InfoSection } from "@/components/InfoPage";
import { legalDetailsComplete } from "@/lib/site-info";
export const metadata: Metadata = { title: "Cookies", description: "Cookies de acceso y seguridad, vídeos externos y controles de privacidad en Tripu.", robots: { index: legalDetailsComplete, follow: true } };
const cookies = [
  ["authjs.session-token", "Mantiene tu sesión iniciada.", "Hasta 30 días; se puede renovar con la actividad."],
  ["authjs.callback-url", "Recuerda adónde volver tras identificarte.", "Sesión del navegador."],
  ["authjs.csrf-token", "Protege las operaciones de acceso frente a solicitudes falsificadas.", "Sesión del navegador."],
  ["authjs.pkce.code_verifier / authjs.state", "Protegen el intercambio de identificación con Google, según el flujo utilizado.", "Hasta 15 minutos; se retiran al completar el flujo."],
];

export default function CookiesPage() {
  return <InfoPage eyebrow="Tú eliges qué se carga" title="Política de cookies" intro="Usamos cookies para que puedas entrar y mantener tu sesión. Los vídeos externos se cargan únicamente cuando decides verlos." legal>
    <InfoSection id="que-son" title="1. Qué son"><p>Las cookies son pequeños datos que el navegador conserva para que un sitio recuerde información entre visitas o peticiones. Algunas permiten iniciar sesión de forma segura; otras, utilizadas por terceros, pueden servir para medir el uso o personalizar contenidos.</p></InfoSection>
    <InfoSection id="necesarias" title="2. Cookies técnicas de Tripu"><p>Estas cookies sirven para las funciones de acceso y seguridad que solicitas. No se ofrece un botón para desactivarlas dentro de Tripu porque bloquearlas puede impedir iniciar sesión.</p><div className="space-y-3">{cookies.map(([name, purpose, duration]) => <div key={name} className="rounded-xl border border-border bg-surface p-4"><h3 className="break-all font-mono text-xs font-semibold text-ink">{name}</h3><p className="mt-2">{purpose}</p><p className="text-xs text-muted">Duración: {duration}</p></div>)}</div><p>En conexiones HTTPS, los nombres llevan habitualmente el prefijo <code>__Secure-</code> o <code>__Host-</code>. El nombre visible puede variar entre el entorno local y el sitio publicado.</p></InfoSection>
    <InfoSection id="videos" title="3. Vídeos de TikTok: activación por vídeo"><p>Visitar una página con vídeos no carga automáticamente el reproductor de TikTok. Cada vídeo muestra primero una explicación y el botón «Permitir y cargar vídeo».</p><p>Si lo pulsas, tu navegador contacta con TikTok, que puede recibir tu dirección IP y datos de navegación y utilizar cookies o tecnologías similares según su <a href="https://www.tiktok.com/legal/page/eea/privacy-policy/es">política de privacidad</a> y su <a href="https://www.tiktok.com/legal/page/global/cookie-policy/es">política de cookies</a>. También puedes abrir el vídeo directamente en TikTok, donde se aplican sus condiciones.</p><p>La autorización se limita a ese reproductor mientras permanezca abierto: no se guarda una preferencia permanente ni se activan los demás vídeos. «Ocultar vídeo» retira el reproductor. No elimina las cookies que TikTok ya haya creado; puedes borrarlas en los ajustes de tu navegador.</p></InfoSection>
    <InfoSection id="otros" title="4. Otros servicios y almacenamiento"><p>Tripu no incorpora actualmente herramientas de publicidad o analítica mediante cookies propias. Sí registra actividad y acciones de compartir en el servidor para estadísticas internas, como se explica en <Link href="/privacidad">Privacidad</Link>.</p><p>Google interviene cuando inicias sesión y Stripe cuando abres una página de pago. Esas páginas externas pueden usar sus propias cookies. Las notificaciones push requieren un permiso independiente del navegador y guardan una suscripción; no se activan al aceptar un vídeo.</p></InfoSection>
    <InfoSection id="control" title="5. Cómo gestionar tus opciones"><p>Puedes seguir usando las partidas sin cargar TikTok. Si ya has abierto un vídeo, utiliza «Ocultar vídeo» para dejar de cargar ese contenido. Para bloquear o borrar cookies, abre los ajustes de privacidad o datos de sitios de tu navegador. Borrar las cookies de Tripu puede cerrar tu sesión.</p><p>Las cookies estrictamente técnicas tienen un tratamiento distinto de las de terceros para otras finalidades. Puedes consultar la <a href="https://www.aepd.es/guias/guia-cookies.pdf">guía de cookies de la AEPD</a> y los datos del titular en el <Link href="/aviso-legal">aviso legal</Link>.</p></InfoSection>
  </InfoPage>;
}
